Repository AY2122S2-CS2103T-T12-1/tp, pull requests merged in 2022-03, with the labels that each got.

#53 Corrections to tests in json files
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
Labels: type.Bug

#55 Add command for finding students by their Covid-19 Status
  src/main/java/seedu/address/logic/commands/FindStatusCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindStatusCommandParser.java
  src/main/java/seedu/address/model/person/POTENTIAL_CHANGES.txt
  src/main/java/seedu/address/model/person/StatusContainsKeywordsPredicate.java
Labels: type.BasicFeaturesV1.2, priority.High, type.Enhancement

#63 Update UG and own PPP
  docs/UserGuide.md
  docs/team/lzf834.md
Labels: priority.Low

#69 Implement JUnit Tests for Status and Status-related functions
  src/test/java/seedu/address/logic/commands/FindStatusTest.java
  src/test/java/seedu/address/logic/parser/FindStatusCommandParserTest.java
  src/test/java/seedu/address/model/person/StatusContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/StatusTest.java
Labels: priority.Low, type.Task

#70 Add filtered list by ClassCode and validation of student
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Status.java
Labels: type.Enhancement

#72 Fix multiple positive cases in class edge case
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, priority.High

#75 Added JUnit tests for ClassCode and related classes.
  src/test/java/seedu/address/logic/commands/FindClassCodeCommandTest.java
  src/test/java/seedu/address/logic/parser/FindClassCodeCommandParserTest.java
  src/test/java/seedu/address/model/person/ClassCodeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/ClassCodeTest.java
Labels: priority.Medium, type.Task

#76 Implement batch update when student recovers
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.Medium, type.Task

#77 Repurpose tags to activities
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedActivity.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/activity/TagTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium, type.Enhancement

#79 Update test files to reflect changes made
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/activity/ActivityTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.BasicFeaturesV1.2, priority.Low, type.Task

#80 Update own PPP
  docs/team/lzf834.md
Labels: priority.Low

#83 New feature added:
  src/main/java/seedu/address/logic/commands/FindActivityCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindActivityCommandParser.java
  src/main/java/seedu/address/model/activity/ActivityContainsKeywordsPredicate.java
Labels: priority.Medium, v1.3

#85 Update fenway17.md
  docs/team/fenway17.md
Labels: PPP update

#86 Added JUnit tests for finding activities command.
  src/test/java/seedu/address/logic/commands/FindActivityCommandTest.java
  src/test/java/seedu/address/logic/parser/FindActivityCommandParserTest.java
  src/test/java/seedu/address/model/activity/ActivityContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.Medium

#84 Update to DG.md
  docs/DeveloperGuide.md
Labels: Doc:DG

#90 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: Doc:DG

#92 Add Batch Update and ClassCode developer guide
  docs/DeveloperGuide.md
Labels: priority.High, Doc:DG

#91 Addition to DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/team/lzf834.md
Labels: priority.High, Doc:DG

#94 Add CSV Compatibility documentation in DG
  docs/DeveloperGuide.md
Labels: priority.High, Doc:DG

#95 Update e0544333 PPP
  docs/team/e0544333.md
Labels: priority.Low

#93 Add logging and exception checking to batch update enhancement
  docs/team/whoisjunhong.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.Low, Documents:Misc, PPP update

#96 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: Doc:DG

#99 Add logging to DeleteCommand
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: priority.Low, v1.3

#100 V1.3
  docs/UserGuide.md
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.UI

#102 Fix UserGuide table formatting
  docs/UserGuide.md
Labels: Doc:UG

#105 Minor changes to UG:
  docs/UserGuide.md
Labels: Doc:UG

#106 Add images to features
  docs/UserGuide.md
  docs/images/user-guide/delete.png
  docs/images/user-guide/edit.png
  docs/images/user-guide/find.png
  docs/images/user-guide/findactivity.png
  docs/images/user-guide/findclasscode.png
  docs/images/user-guide/findstatus.png
  docs/images/user-guide/invalidcommand.png
  docs/images/user-guide/list.png
Labels: Doc:UG

#107 V1.3 UserGuide Changes
  docs/UserGuide.md
  docs/team/lzf834.md
Labels: Doc:UG, PPP update, v1.3

#109 Updated userguide.md and changed application top bar to state "Ultimate Divoc Tracker" instead of "Address Book"
  docs/UserGuide.md
  docs/team/fenway17.md
  src/main/resources/view/MainWindow.fxml
Labels: Doc:UG, type.UI

#114 Changes to UG:
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/images/UdtGuiWithLabels.png
  docs/images/udtgui.PNG
  docs/images/user-guide/edit.png
Labels: priority.High, Doc:UG

#118 Fix batch update edge cases for AddCommand and DeleteCommand
  docs/team/whoisjunhong.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, severity.Medium, v1.3

#121 Fix bg color
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonListPanel.fxml
Labels: severity.VeryLow, v1.3, type.UI
